"""Repository-specific query services."""

from __future__ import annotations

from watchtower_core.utils.module_exports import lazy_module_getattr

__all__ = [
    "AcceptanceContractQueryService",
    "AcceptanceContractSearchParams",
    "ArtifactQueryService",
    "ArtifactSearchParams",
    "AuthorityMapQueryService",
    "AuthorityMapSearchParams",
    "CommandQueryService",
    "CommandSearchParams",
    "CoordinationQueryResult",
    "CoordinationQueryService",
    "CoordinationSearchParams",
    "PlanCloseoutQueryService",
    "PlanCloseoutSearchParams",
    "DiscrepancyQueryService",
    "DiscrepancySearchParams",
    "PlanEvidenceQueryService",
    "PlanEvidenceSearchParams",
    "ValidationEvidenceQueryService",
    "ValidationEvidenceSearchParams",
    "FoundationQueryService",
    "FoundationSearchParams",
    "InitiativeQueryService",
    "InitiativeSearchParams",
    "ProjectQueryService",
    "ProjectSearchParams",
    "ReadinessQueryService",
    "ReadinessSearchParams",
    "ReferenceQueryService",
    "ReferenceSearchParams",
    "RepositoryPathQueryService",
    "RepositoryPathSearchParams",
    "PlanReviewQueryService",
    "PlanReviewSearchParams",
    "StandardQueryService",
    "StandardSearchParams",
    "TaskQueryService",
    "TaskSearchParams",
    "TraceabilityQueryService",
    "WorkflowQueryService",
    "WorkflowSearchParams",
]

_EXPORT_MODULES = {
    "AcceptanceContractQueryService": "watchtower_core.plan_runtime.query.acceptance",
    "AcceptanceContractSearchParams": "watchtower_core.plan_runtime.query.acceptance",
    "ArtifactQueryService": "watchtower_core.plan_runtime.query.artifacts",
    "ArtifactSearchParams": "watchtower_core.plan_runtime.query.artifacts",
    "AuthorityMapQueryService": "watchtower_core.query.authority",
    "AuthorityMapSearchParams": "watchtower_core.query.authority",
    "CommandQueryService": "watchtower_core.query.commands",
    "CommandSearchParams": "watchtower_core.query.commands",
    "CoordinationQueryResult": "watchtower_core.plan_runtime.query.coordination",
    "CoordinationQueryService": "watchtower_core.plan_runtime.query.coordination",
    "CoordinationSearchParams": "watchtower_core.plan_runtime.query.coordination",
    "PlanCloseoutQueryService": "watchtower_core.plan_runtime.query.closeouts",
    "PlanCloseoutSearchParams": "watchtower_core.plan_runtime.query.closeouts",
    "DiscrepancyQueryService": "watchtower_core.plan_runtime.query.discrepancies",
    "DiscrepancySearchParams": "watchtower_core.plan_runtime.query.discrepancies",
    "PlanEvidenceQueryService": "watchtower_core.plan_runtime.query.plan_evidence",
    "PlanEvidenceSearchParams": "watchtower_core.plan_runtime.query.plan_evidence",
    "ValidationEvidenceQueryService": "watchtower_core.plan_runtime.query.evidence",
    "ValidationEvidenceSearchParams": "watchtower_core.plan_runtime.query.evidence",
    "FoundationQueryService": "watchtower_core.plan_runtime.query.foundations",
    "FoundationSearchParams": "watchtower_core.plan_runtime.query.foundations",
    "InitiativeQueryService": "watchtower_core.plan_runtime.query.initiatives",
    "InitiativeSearchParams": "watchtower_core.plan_runtime.query.initiatives",
    "ProjectQueryService": "watchtower_core.plan_runtime.query.projects",
    "ProjectSearchParams": "watchtower_core.plan_runtime.query.projects",
    "ReadinessQueryService": "watchtower_core.plan_runtime.query.readiness",
    "ReadinessSearchParams": "watchtower_core.plan_runtime.query.readiness",
    "ReferenceQueryService": "watchtower_core.plan_runtime.query.references",
    "ReferenceSearchParams": "watchtower_core.plan_runtime.query.references",
    "RepositoryPathQueryService": "watchtower_core.plan_runtime.query.repository",
    "RepositoryPathSearchParams": "watchtower_core.plan_runtime.query.repository",
    "PlanReviewQueryService": "watchtower_core.plan_runtime.query.reviews",
    "PlanReviewSearchParams": "watchtower_core.plan_runtime.query.reviews",
    "StandardQueryService": "watchtower_core.plan_runtime.query.standards",
    "StandardSearchParams": "watchtower_core.plan_runtime.query.standards",
    "TaskQueryService": "watchtower_core.plan_runtime.query.tasks",
    "TaskSearchParams": "watchtower_core.plan_runtime.query.tasks",
    "TraceabilityQueryService": "watchtower_core.plan_runtime.query.traceability",
    "WorkflowQueryService": "watchtower_core.query.workflows",
    "WorkflowSearchParams": "watchtower_core.query.workflows",
}

__getattr__ = lazy_module_getattr(
    module_name=__name__,
    export_modules=_EXPORT_MODULES,
)
