"""Repository-specific query services."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "AcceptanceContractQueryService",
    "AcceptanceContractSearchParams",
    "ArtifactQueryService",
    "ArtifactSearchParams",
    "AuthorityMapQueryService",
    "AuthorityMapSearchParams",
    "CommandQueryService",
    "CommandSearchParams",
    "CoordinationQueryResult",
    "CoordinationQueryService",
    "CoordinationSearchParams",
    "DiscrepancyQueryService",
    "DiscrepancySearchParams",
    "DecisionQueryService",
    "DecisionSearchParams",
    "DesignDocumentQueryService",
    "DesignDocumentSearchParams",
    "ValidationEvidenceQueryService",
    "ValidationEvidenceSearchParams",
    "FoundationQueryService",
    "FoundationSearchParams",
    "InitiativeQueryService",
    "InitiativeSearchParams",
    "PlanningCatalogQueryService",
    "PlanningCatalogSearchParams",
    "PrdQueryService",
    "PrdSearchParams",
    "ProjectQueryService",
    "ProjectSearchParams",
    "ReadinessQueryService",
    "ReadinessSearchParams",
    "ReferenceQueryService",
    "ReferenceSearchParams",
    "RepositoryPathQueryService",
    "RepositoryPathSearchParams",
    "StandardQueryService",
    "StandardSearchParams",
    "TaskQueryService",
    "TaskSearchParams",
    "TraceabilityQueryService",
    "WorkflowQueryService",
    "WorkflowSearchParams",
]

_EXPORT_MODULES = {
    "AcceptanceContractQueryService": "watchtower_core.repo_ops.query.acceptance",
    "AcceptanceContractSearchParams": "watchtower_core.repo_ops.query.acceptance",
    "ArtifactQueryService": "watchtower_core.repo_ops.query.artifacts",
    "ArtifactSearchParams": "watchtower_core.repo_ops.query.artifacts",
    "AuthorityMapQueryService": "watchtower_core.repo_ops.query.authority",
    "AuthorityMapSearchParams": "watchtower_core.repo_ops.query.authority",
    "CommandQueryService": "watchtower_core.repo_ops.query.commands",
    "CommandSearchParams": "watchtower_core.repo_ops.query.commands",
    "CoordinationQueryResult": "watchtower_core.repo_ops.query.coordination",
    "CoordinationQueryService": "watchtower_core.repo_ops.query.coordination",
    "CoordinationSearchParams": "watchtower_core.repo_ops.query.coordination",
    "DecisionQueryService": "watchtower_core.repo_ops.query.decisions",
    "DecisionSearchParams": "watchtower_core.repo_ops.query.decisions",
    "DiscrepancyQueryService": "watchtower_core.repo_ops.query.discrepancies",
    "DiscrepancySearchParams": "watchtower_core.repo_ops.query.discrepancies",
    "DesignDocumentQueryService": "watchtower_core.repo_ops.query.designs",
    "DesignDocumentSearchParams": "watchtower_core.repo_ops.query.designs",
    "ValidationEvidenceQueryService": "watchtower_core.repo_ops.query.evidence",
    "ValidationEvidenceSearchParams": "watchtower_core.repo_ops.query.evidence",
    "FoundationQueryService": "watchtower_core.repo_ops.query.foundations",
    "FoundationSearchParams": "watchtower_core.repo_ops.query.foundations",
    "InitiativeQueryService": "watchtower_core.repo_ops.query.initiatives",
    "InitiativeSearchParams": "watchtower_core.repo_ops.query.initiatives",
    "PlanningCatalogQueryService": "watchtower_core.repo_ops.query.planning",
    "PlanningCatalogSearchParams": "watchtower_core.repo_ops.query.planning",
    "PrdQueryService": "watchtower_core.repo_ops.query.prds",
    "PrdSearchParams": "watchtower_core.repo_ops.query.prds",
    "ProjectQueryService": "watchtower_core.repo_ops.query.projects",
    "ProjectSearchParams": "watchtower_core.repo_ops.query.projects",
    "ReadinessQueryService": "watchtower_core.repo_ops.query.readiness",
    "ReadinessSearchParams": "watchtower_core.repo_ops.query.readiness",
    "ReferenceQueryService": "watchtower_core.repo_ops.query.references",
    "ReferenceSearchParams": "watchtower_core.repo_ops.query.references",
    "RepositoryPathQueryService": "watchtower_core.repo_ops.query.repository",
    "RepositoryPathSearchParams": "watchtower_core.repo_ops.query.repository",
    "StandardQueryService": "watchtower_core.repo_ops.query.standards",
    "StandardSearchParams": "watchtower_core.repo_ops.query.standards",
    "TaskQueryService": "watchtower_core.repo_ops.query.tasks",
    "TaskSearchParams": "watchtower_core.repo_ops.query.tasks",
    "TraceabilityQueryService": "watchtower_core.repo_ops.query.traceability",
    "WorkflowQueryService": "watchtower_core.repo_ops.query.workflows",
    "WorkflowSearchParams": "watchtower_core.repo_ops.query.workflows",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(import_module(module_name), name)
