"""Repository-specific sync services."""

from __future__ import annotations

from watchtower_core.utils.module_exports import lazy_module_getattr

__all__ = [
    "AllSyncResult",
    "AllSyncService",
    "COMMAND_INDEX_ARTIFACT_PATH",
    "CommandIndexSyncService",
    "COORDINATION_SYNC_GROUP",
    "COORDINATION_INDEX_ARTIFACT_PATH",
    "COORDINATION_TRACKING_DOCUMENT_PATH",
    "CoordinationSyncService",
    "CoordinationIndexSyncService",
    "CoordinationTrackingSyncService",
    "FOUNDATION_INDEX_ARTIFACT_PATH",
    "FoundationIndexSyncService",
    "GitHubTaskSyncParams",
    "GitHubTaskSyncService",
    "INITIATIVE_INDEX_ARTIFACT_PATH",
    "INITIATIVE_TRACKING_DOCUMENT_PATH",
    "InitiativeIndexSyncService",
    "InitiativeTrackingSyncService",
    "REFERENCE_INDEX_ARTIFACT_PATH",
    "ReferenceIndexSyncService",
    "ROUTE_INDEX_ARTIFACT_PATH",
    "RouteIndexSyncService",
    "REPOSITORY_PATH_INDEX_ARTIFACT_PATH",
    "RepositoryPathIndexSyncService",
    "SYNC_TARGET_SPECS",
    "sync_target_specs_for_group",
    "STANDARD_INDEX_ARTIFACT_PATH",
    "StandardIndexSyncService",
    "SyncTargetGroup",
    "SyncTargetSpec",
    "TASK_INDEX_ARTIFACT_PATH",
    "TASK_TRACKING_DOCUMENT_PATH",
    "TaskIndexSyncService",
    "TaskTrackingSyncService",
    "TRACEABILITY_INDEX_ARTIFACT_PATH",
    "TraceabilityIndexSyncService",
    "WORKFLOW_INDEX_ARTIFACT_PATH",
    "WorkflowIndexSyncService",
]

_EXPORT_MODULES = {
    "AllSyncResult": "watchtower_core.plan_runtime.sync.all",
    "AllSyncService": "watchtower_core.plan_runtime.sync.all",
    "COMMAND_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.command_index",
    "CommandIndexSyncService": "watchtower_core.plan_runtime.sync.command_index",
    "COORDINATION_SYNC_GROUP": "watchtower_core.plan_runtime.sync.registry",
    "COORDINATION_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.coordination_index",
    "COORDINATION_TRACKING_DOCUMENT_PATH": "watchtower_core.plan_runtime.sync.coordination_tracking",
    "CoordinationSyncService": "watchtower_core.plan_runtime.sync.coordination",
    "CoordinationIndexSyncService": "watchtower_core.plan_runtime.sync.coordination_index",
    "CoordinationTrackingSyncService": "watchtower_core.plan_runtime.sync.coordination_tracking",
    "FOUNDATION_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.foundation_index",
    "FoundationIndexSyncService": "watchtower_core.plan_runtime.sync.foundation_index",
    "GitHubTaskSyncParams": "watchtower_core.plan_runtime.sync.github_tasks",
    "GitHubTaskSyncService": "watchtower_core.plan_runtime.sync.github_tasks",
    "INITIATIVE_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.initiative_index",
    "INITIATIVE_TRACKING_DOCUMENT_PATH": "watchtower_core.plan_runtime.sync.initiative_tracking",
    "InitiativeIndexSyncService": "watchtower_core.plan_runtime.sync.initiative_index",
    "InitiativeTrackingSyncService": "watchtower_core.plan_runtime.sync.initiative_tracking",
    "REFERENCE_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.reference_index",
    "ReferenceIndexSyncService": "watchtower_core.plan_runtime.sync.reference_index",
    "ROUTE_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.route_index",
    "RouteIndexSyncService": "watchtower_core.plan_runtime.sync.route_index",
    "REPOSITORY_PATH_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.repository_paths",
    "RepositoryPathIndexSyncService": "watchtower_core.plan_runtime.sync.repository_paths",
    "SYNC_TARGET_SPECS": "watchtower_core.plan_runtime.sync.registry",
    "sync_target_specs_for_group": "watchtower_core.plan_runtime.sync.registry",
    "STANDARD_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.standard_index",
    "StandardIndexSyncService": "watchtower_core.plan_runtime.sync.standard_index",
    "SyncTargetGroup": "watchtower_core.plan_runtime.sync.registry",
    "SyncTargetSpec": "watchtower_core.plan_runtime.sync.registry",
    "TASK_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.task_index",
    "TASK_TRACKING_DOCUMENT_PATH": "watchtower_core.plan_runtime.sync.task_tracking",
    "TaskIndexSyncService": "watchtower_core.plan_runtime.sync.task_index",
    "TaskTrackingSyncService": "watchtower_core.plan_runtime.sync.task_tracking",
    "TRACEABILITY_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.traceability",
    "TraceabilityIndexSyncService": "watchtower_core.plan_runtime.sync.traceability",
    "WORKFLOW_INDEX_ARTIFACT_PATH": "watchtower_core.plan_runtime.sync.workflow_index",
    "WorkflowIndexSyncService": "watchtower_core.plan_runtime.sync.workflow_index",
}

__getattr__ = lazy_module_getattr(
    module_name=__name__,
    export_modules=_EXPORT_MODULES,
)
